const {chromium} = require(process.env.SENDMAILS_PLAYWRIGHT || 'playwright');
const assert = require('assert/strict');
const fs = require('fs');
const path = require('path');
const os = require('os');
const database = process.env.SENDMAILS_TEST_DATABASE || '';
assert.match(database, /^SendMails_Agility_Test_[a-f0-9]{12}$/);
const storage = path.join(os.tmpdir(), database);
const artifactDir = process.env.SENDMAILS_ARTIFACT_DIR || path.join(os.tmpdir(), 'sendmails-ui-artifacts');
fs.mkdirSync(artifactDir, {recursive:true});
// Simulate only the fixture heartbeat; never run a transport or a scheduled task.
function heartbeat(error = '', stale = false) {
    const controlPath = path.join(storage, 'worker-control-1.json');
    const control = fs.existsSync(controlPath) ? JSON.parse(fs.readFileSync(controlPath, 'utf8')) : {revision:0};
    const now = Math.floor(Date.now()/1000) - (stale ? 181 : 0);
    fs.writeFileSync(path.join(storage,'worker-status.json'), JSON.stringify({status:'idle',updated_at:now,active_branch:null,branches:{1:{checked_at:now,control_revision:control.revision,error}}}));
}
(async () => {
    heartbeat();
    const browser = await chromium.launch({headless:true,channel:'msedge'});
    try {
        const page = await browser.newPage({viewport:{width:1440,height:1000}});
        const errors=[]; page.on('pageerror', error=>errors.push(error.message));
        await page.goto('http://127.0.0.1:8765/activity.php?kind=campaign');
        const button=page.locator('#serviceStatusButton');
        assert.ok((await button.getAttribute('class')).includes('is-ok'));
        assert.ok(await page.evaluate(()=>!!(document.getElementById('serviceStatusButton').compareDocumentPosition(document.querySelector('.topbar-branch')) & Node.DOCUMENT_POSITION_FOLLOWING)));
        assert.equal(await page.locator('.nav a.active').innerText(),'Ver campañas');
        await button.click();
        await page.waitForSelector('#serviceDialog[open]');
        await page.locator('#stopService').click();
        await page.waitForFunction(()=>document.getElementById('serviceStatusButton').textContent.includes('Detenido'));
        assert.ok((await button.getAttribute('class')).includes('is-error'));
        await page.waitForFunction(()=>getComputedStyle(document.getElementById('serviceStatusButton')).backgroundColor==='rgb(185, 28, 28)');
        let response=await page.request.get('http://127.0.0.1:8765/worker_control.php?branch_id=99999',{headers:{Accept:'application/json'}});
        assert.equal(response.status(),409,'No controlar otra sucursal desde una pestaña anterior');
        response=await page.request.post('http://127.0.0.1:8765/worker_control.php',{headers:{Accept:'application/json'},data:{branch_id:1,action:'start',revision:1}});
        assert.equal(response.status(),419,'Rechazar control sin CSRF');
        await page.locator('#startService').click();
        await page.waitForFunction(()=>document.getElementById('serviceStatusButton').textContent.includes('Por iniciar'));
        heartbeat();
        await page.locator('#closeService').click();await button.click();
        await page.waitForFunction(()=>document.getElementById('serviceStatusButton').classList.contains('is-ok'));
        await page.waitForFunction(()=>getComputedStyle(document.getElementById('serviceStatusButton')).backgroundColor==='rgb(21, 128, 61)');
        await page.screenshot({path:path.join(artifactDir,'service-desktop.png')});
        heartbeat('Error de envío simulado');
        await page.locator('#closeService').click();await button.click();
        await page.waitForFunction(()=>document.getElementById('serviceStatusButton').textContent.includes('Con error'));
        assert.match(await page.locator('#serviceDetail').innerText(),/Error de envío simulado/);
        heartbeat('',true);
        await page.locator('#closeService').click();await button.click();
        await page.waitForFunction(()=>document.getElementById('serviceStatusButton').textContent.includes('Sin actividad'));
        heartbeat();
        await page.locator('#closeService').click();
        await page.goto('http://127.0.0.1:8765/purge.php');
        assert.equal(await page.locator('#purgeBranch').inputValue(),'0');
        await page.locator('#previewPurge').click();
        await page.waitForSelector('#purgeReview');
        assert.equal(await page.locator('.alert.error:visible').count(),0);
        assert.match(await page.locator('#purgeReview').innerText(),/UI purge fixture/);
        await page.screenshot({path:path.join(artifactDir,'purge-desktop.png'),fullPage:true});
        await page.locator('#purgeChannel').selectOption('email');
        assert.equal(await page.locator('#purgeReview').isVisible(),false,'Cambiar filtros invalida visualmente la confirmación anterior');
        await page.locator('#previewPurge').click();
        await page.waitForSelector('#purgeConfirm');
        await page.locator('#purgeConfirm input[type=checkbox]').check();
        await page.locator('#confirmPurge').click();
        await page.waitForSelector('.alert.success');
        assert.match(await page.locator('.alert.success').innerText(),/Purga completada/);
        await page.locator('#previewPurge').click();
        await page.waitForSelector('#purgeReview');
        assert.match(await page.locator('#purgeReview').innerText(),/No hay lotes/);
        await page.setViewportSize({width:390,height:844});
        await page.goto('http://127.0.0.1:8765/index.php');
        await page.locator('#serviceStatusButton').click();
        await page.waitForSelector('#serviceDialog[open]');
        await page.waitForFunction(()=>!document.getElementById('stopService').disabled);
        await page.screenshot({path:path.join(artifactDir,'service-mobile.png')});
        assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'Sin desborde horizontal');
        await page.keyboard.press('Escape');
        assert.equal(await page.locator('#serviceDialog').isVisible(),false);
        assert.deepEqual(errors,[]);
        console.log('OPERATIONS BROWSER OK: indicador, modal, stop/start por sucursal, errores, CSRF, purga con vista previa y confirmacion, escritorio/movil.');
    } finally { await browser.close(); }
})().catch(error=>{console.error(error);process.exit(1);});
