const { chromium } = require(process.env.SENDMAILS_PLAYWRIGHT || 'playwright');
const fs = require('fs');
const path = require('path');
const assert = require('assert/strict');
const artifactDir = process.env.SENDMAILS_ARTIFACT_DIR || path.join(require('os').tmpdir(), 'sendmails-ui-artifacts');
fs.mkdirSync(artifactDir, {recursive:true});
(async () => {
    const browser = await chromium.launch({headless: true, channel: 'msedge'});
    const page = await browser.newPage({viewport: {width: 1440, height: 1050}});
    const errors = [];
    page.on('pageerror', error => errors.push(error.message));
    for (const url of ['campaigns.php', 'invoice_sends.php']) {
        const response = await page.goto('http://127.0.0.1:8765/' + url);
        assert.equal(response.status(), 200, url);
        assert.equal(await page.locator('.alert.error:visible').count(), 0, url + ': error en el listado');
        assert.doesNotMatch(await page.locator('body').innerText(), /SQLSTATE|Fatal error/);
        assert.ok(await page.locator('h1').isVisible(), url + ': titulo visible');
    }
    console.log('MANAGEMENT BROWSER OK: campañas y facturas cargan sin errores SQL.');
    if (process.argv.includes('--management-only')) {
        assert.deepEqual(errors, []);
        await browser.close();
        return;
    }
    await page.goto('http://127.0.0.1:8765/send.php');
    await page.waitForFunction(() => document.getElementById('pageInfo')?.textContent.includes('4.000'));
    await page.waitForFunction(() => !document.getElementById('composeForm').hasAttribute('aria-busy'));
    assert.equal(await page.locator('#loadDraft').isEnabled(), true);
    assert.equal(await page.locator('#recipientRows tr').count(), 50);
    await page.locator('#selectAll').click();
    await page.waitForFunction(() => document.getElementById('selectionCount').textContent.includes('4.000'));
    await page.locator('#nextPage').click();
    await page.waitForFunction(() => document.getElementById('pageInfo').textContent.includes('Página 2'));
    assert.equal(await page.locator('#recipientRows input:checked').count(),50);
    await page.locator('[data-panel="1"] [data-step="2"]').click();
    await page.locator('#name').fill('Campaña browser 4000');
    await page.locator('#saveDraft').click();
    await page.waitForFunction(() => document.getElementById('saveStatus').textContent.includes('guardado'));
    await page.waitForFunction(() => !document.getElementById('composeForm').hasAttribute('aria-busy'));
    assert.equal(await page.locator('#loadDraft').isEnabled(), true);
    await page.reload();
    await page.waitForFunction(() => document.getElementById('selectionCount').textContent.includes('4.000'));
    await page.locator('#reviewTop').click();
    await page.waitForSelector('[data-panel="3"]:visible');
    assert.match(await page.locator('#reviewCounts').innerText(), /4\.000/);
    await page.screenshot({path:path.join(artifactDir,'review-desktop.png'),fullPage:true});
    await page.locator('#confirmSend').click();
    await page.waitForURL(/activity\.php/);
    assert.match(await page.locator('#liveActivity').innerText(), /Campaña browser 4000/);
    await page.goto('http://127.0.0.1:8765/invoices.php');
    await page.waitForFunction(() => !document.getElementById('composeForm').hasAttribute('aria-busy'));
    await page.locator('#due_date').fill('2026-09-30');
    await page.locator('#searchRows').click();
    await page.waitForFunction(() => document.getElementById('pageInfo').textContent.includes('4.000'));
    await page.locator('#selectAll').click();
    await page.waitForFunction(() => document.getElementById('selectionCount').textContent.includes('4.000'));
    await page.screenshot({path:path.join(artifactDir,'invoices-desktop.png'),fullPage:true});
    await page.locator('[data-panel="1"] [data-step="2"]').click();
    await page.locator('#name').fill('Facturas browser 4000');
    await page.locator('#reviewSend').click();
    await page.waitForSelector('[data-panel="3"]:visible');
    assert.equal(await page.locator('#reviewTest').isVisible(),true);
    await page.locator('#confirmSend').click();
    await page.waitForURL(/activity\.php/);
    await page.setViewportSize({width:390,height:844});
    await page.goto('http://127.0.0.1:8765/send.php');
    await page.waitForFunction(() => document.getElementById('pageInfo')?.textContent.includes('4.000'));
    await page.screenshot({path:path.join(artifactDir,'campaign-mobile.png'),fullPage:true});
    assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1), 'No page-level horizontal overflow');
    // Attachments remain available after saving/reloading a shared draft.
    await page.goto('http://127.0.0.1:8765/template_edit.php');
    await page.locator('#name').fill('Plantilla con adjunto compartido');
    await page.locator('#subject').fill('Adjunto de prueba');
    await page.locator('input[type=file][name="attachments[]"]').setInputFiles({name:'ejemplo.txt',mimeType:'text/plain',buffer:Buffer.from('fixture attachment')});
    await page.locator('button[value=save_draft]').click();
    await page.waitForURL(/draft=/);
    assert.match(await page.locator('body').innerText(),/ejemplo\.txt/);
    await page.reload();
    assert.match(await page.locator('body').innerText(),/ejemplo\.txt/);
    await page.locator('button[value=save]').click();
    await page.waitForURL(/id=/);
    assert.match(await page.locator('body').innerText(),/ejemplo\.txt/);
    assert.deepEqual(errors,[]);
    console.log('BROWSER OK: 4000 campaign + invoices, selection persistence, shared draft, attachments, review, confirmation, desktop/mobile.');
    await browser.close();
})().catch(error => { console.error(error); process.exit(1); });
